name: Main Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      YandexTrackerOptions__OAuthToken: ${{ secrets.YANDEXTRACKER_OAUTHTOKEN }}
      YandexTrackerOptions__Organization: ${{ secrets.YANDEXTRACKER_ORGANIZATION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 6.0.x

      - name: Install dependencies
        run: dotnet restore    
        
      - name: Build
        run: dotnet build ./Mindbox.YandexTracker.sln --configuration Release --no-restore
     
      - name: Test
        run: dotnet test --no-restore
     
      - name: Pack
        run: dotnet pack ./Mindbox.YandexTracker.sln -c Release -p:BuildNumber=${{ github.run_number }}

      - name: Publish
        run: dotnet nuget push **/*.nupkg -k ${{secrets.MINDBOX_NUGET_AUTH_TOKEN}} -s https://api.nuget.org/v3/index.json