name: Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      YandexTrackerOptions__OAuthToken: ${{ secrets.YANDEXTRACKER_OAUTHTOKEN }}
      YandexTrackerOptions__Organization: ${{ secrets.YANDEXTRACKER_ORGANIZATION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
        
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Ensure Version Bump
        uses: mindbox-cloud/github-actions/ensure-bump@master
        with:
          abstractionsPath: 'Mindbox.YandexTracker.Abstractions'
        
      - name: Install dependencies
        run: dotnet restore      

      - name: Build
        run: dotnet build ./Mindbox.YandexTracker.sln --configuration Release --no-restore
